# Generated by Django 2.1.7 on 2019-02-17 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='john smith', max_length=200)),
                ('content', models.TextField(default='some text')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 2, 17, 1, 18, 57, 253509, tzinfo=utc))),
            ],
        ),
    ]
