# Generated by Django 2.1.7 on 2019-02-17 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 1, 20, 9, 761260, tzinfo=utc)),
        ),
    ]
