# Generated by Django 2.1.7 on 2019-02-19 00:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190217_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 0, 19, 56, 179862, tzinfo=utc)),
        ),
    ]
